# Generated by Django 6.1 on 2026-08-18 02:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('abreviacao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comissao',
            },
        ),
        migrations.CreateModel(
            name='Comite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('abreviacao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'comite',
            },
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='GrupoTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('abreviacao', models.CharField(max_length=20, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'grupo_trabalho',
            },
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('documento', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
                ('senha', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('afastado', 'Afastado'), ('expulso', 'Expulso')], default='ativo', max_length=20)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'pessoa',
            },
        ),
        migrations.CreateModel(
            name='PessoaCalouro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('em processo', 'Em Processo'), ('membro', 'Membro')], default='em processo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pessoa', models.ForeignKey(db_column='fk_pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='calouros', to='core.pessoa')),
            ],
            options={
                'db_table': 'pessoa_calouro',
            },
        ),
        migrations.CreateModel(
            name='PessoaMembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(db_column='fk_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.departamento')),
                ('pessoa', models.ForeignKey(db_column='fk_pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='membros', to='core.pessoa')),
            ],
            options={
                'db_table': 'pessoa_membro',
            },
        ),
        migrations.CreateModel(
            name='UserComissao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado'), ('afastado', 'Afastado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comissao', models.ForeignKey(db_column='fk_comissao', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.comissao')),
                ('departamento', models.ForeignKey(db_column='fk_departamento', on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_usuario', to='core.departamento')),
                ('pessoa', models.ForeignKey(db_column='fk_pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='comissoes_usuario', to='core.pessoa')),
            ],
            options={
                'db_table': 'user_comissao',
            },
        ),
        migrations.CreateModel(
            name='UserComite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('encerrado', 'Encerrado')], default='ativo', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('comite', models.ForeignKey(db_column='fk_comite', on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to='core.comite')),
                ('pessoa', models.ForeignKey(db_column='fk_pessoa', on_delete=django.db.models.deletion.CASCADE, related_name='comites_usuario', to='core.pessoa')),
                ('presidente', models.ForeignKey(blank=True, db_column='fk_presidente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comites_presididos', to='core.pessoa')),
            ],
            options={
                'db_table': 'user_comite',
            },
        ),
        migrations.CreateModel(
            name='UserCoordenacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_at', models.DateTimeField()),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('presidente', models.ForeignKey(db_column='fk_presidente', on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes_presididas', to='core.pessoa')),
                ('vice1', models.ForeignKey(db_column='fk_vice1', on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes_vice1', to='core.pessoa')),
                ('vice2', models.ForeignKey(db_column='fk_vice2', on_delete=django.db.models.deletion.CASCADE, related_name='coordenacoes_vice2', to='core.pessoa')),
            ],
            options={
                'db_table': 'user_coordenacao',
            },
        ),
    ]
